name: Error Checker

on: [ push, pull_request ]
jobs:
  build:
    strategy:
      matrix:
        java: [
            16
        ]
        os: [ ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Check If Running In Template Repository
        if: ${{ github.event.repository.name == 'FabricTemplateMod' }}
        run: exit 0
      - name: Check If Initial Commit
        if: ${{ github.event.commits[0].message == 'Initial commit' }}
        run: exit 0
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Capture Build Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
